# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0)),
                ('charge_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'account_log',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('marked', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '通知信息',
                'verbose_name_plural': '通知信息',
                'db_table': 'alert',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_service.Role')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'db_table': 'limit',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='PlayerBindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bound', models.BooleanField(default=False)),
                ('contract_time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Player')),
            ],
            options={
                'verbose_name': '玩家联系记录',
                'verbose_name_plural': '玩家联系记录',
                'db_table': 'player_bind_info',
            },
        ),
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Player')),
            ],
            options={
                'verbose_name': '玩家注册信息',
                'verbose_name_plural': '玩家注册信息',
                'db_table': 'register_info',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='customer_service.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginname',
            field=models.CharField(max_length=100, unique=True, verbose_name='login name'),
        ),
        migrations.AddField(
            model_name='playerbindinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountlog',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Game'),
        ),
        migrations.AddField(
            model_name='accountlog',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Player'),
        ),
        migrations.AddField(
            model_name='accountlog',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
