# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_auto_20170920_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('parent', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='RoleBindMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.Role')),
            ],
            options={
                'verbose_name': '菜单权限',
                'verbose_name_plural': '菜单权限',
                'db_table': 'role_bind_menu',
            },
        ),
    ]
