# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0005_auto_20170923_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order_index',
            field=models.IntegerField(null=True),
        ),
    ]
