# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_menu_order_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '联系结果',
                'verbose_name_plural': '联系结果',
                'db_table': 'contract_result',
            },
        ),
        migrations.AddField(
            model_name='playerbindinfo',
            name='contract_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_service.ContractResult'),
        ),
    ]
