# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0008_player_locked_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('path', models.CharField(max_length=200, verbose_name='文件路径')),
                ('export_time', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'verbose_name': '文件导出',
                'verbose_name_plural': '文件导出',
                'db_table': 'player_export',
            },
        ),
        migrations.CreateModel(
            name='PlayerImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('path', models.CharField(max_length=200, verbose_name='文件路径')),
                ('import_time', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'verbose_name': '文件导入',
                'verbose_name_plural': '文件导入',
                'db_table': 'player_import',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='imported_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_service.PlayerImport'),
        ),
    ]
