# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0009_auto_20170927_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerimport',
            name='stored_name',
            field=models.CharField(max_length=100, null=True, verbose_name='保存文件名称'),
        ),
    ]
