# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0011_auto_20170928_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerbindinfo',
            name='in_effect',
            field=models.BooleanField(default=True),
        ),
    ]
