# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0012_auto_20170929_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='export_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_to', to='customer_service.PlayerExport'),
        ),
        migrations.AlterField(
            model_name='player',
            name='imported_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_from', to='customer_service.PlayerImport'),
        ),
    ]
