# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0013_auto_20171008_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractresult',
            name='bind',
            field=models.BooleanField(default=False),
        ),
    ]
