# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0014_contractresult_bind'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
