# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0015_player_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='locked_by',
            new_name='locked_by_user',
        ),
        migrations.AddField(
            model_name='player',
            name='charge_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='charge_money_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='login_count',
            field=models.IntegerField(null=True),
        ),
    ]
