# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0016_auto_20171012_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_contact_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
