# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0017_player_current_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractresult',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playerimport',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
