# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0018_auto_20171016_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractresult',
            name='process',
            field=models.CharField(default='', max_length=20),
        ),
    ]
