# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0020_auto_20171016_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('object_id', models.IntegerField(null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'operator_log',
            },
        ),
        migrations.AlterField(
            model_name='accountlog',
            name='charge_time',
            field=models.DateTimeField(null=True),
        ),
    ]
