# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0021_auto_20171027_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_account_log_id',
            field=models.IntegerField(null=True, verbose_name='最近的充值记录ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_contact_id',
            field=models.IntegerField(null=True, verbose_name='最近的联系记录ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_login_info_id',
            field=models.IntegerField(null=True, verbose_name='最近登录信息ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='register_from_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_service.Game', verbose_name='账号注册游戏'),
        ),
        migrations.AddField(
            model_name='player',
            name='register_from_game_time',
            field=models.DateTimeField(null=True, verbose_name='账号注册时间'),
        ),
        migrations.AlterField(
            model_name='operatorlog',
            name='object_repr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='account',
            field=models.CharField(max_length=100, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='player',
            name='charge_count',
            field=models.IntegerField(null=True, verbose_name='充值次数'),
        ),
        migrations.AlterField(
            model_name='player',
            name='charge_money_total',
            field=models.FloatField(null=True, verbose_name='充值总额'),
        ),
        migrations.AlterField(
            model_name='player',
            name='come_from',
            field=models.CharField(max_length=100, null=True, verbose_name='所属渠道'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_contact_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to=settings.AUTH_USER_MODEL, verbose_name='当前查看客服'),
        ),
        migrations.AlterField(
            model_name='player',
            name='export_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_to', to='customer_service.PlayerExport', verbose_name='导出到'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_count',
            field=models.IntegerField(null=True, verbose_name='注册游戏数量'),
        ),
        migrations.AlterField(
            model_name='player',
            name='imported_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_from', to='customer_service.PlayerImport', verbose_name='导入自'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='player',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='是否锁定'),
        ),
        migrations.AlterField(
            model_name='player',
            name='locked_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='锁定客服'),
        ),
        migrations.AlterField(
            model_name='player',
            name='locked_time',
            field=models.DateTimeField(null=True, verbose_name='锁定时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='login_count',
            field=models.IntegerField(null=True, verbose_name='登录次数'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='player',
            name='qq',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='时间戳'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='姓名'),
        ),
    ]
