# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0022_auto_20171102_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlog',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_service.Game'),
        ),
    ]
