# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0023_auto_20171103_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='export_to',
            field=models.IntegerField(null=True, verbose_name='导出到'),
        ),
        migrations.AlterField(
            model_name='player',
            name='imported_from',
            field=models.IntegerField(null=True, verbose_name='导入自'),
        ),
    ]
