# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0024_auto_20171103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='timing',
            field=models.BooleanField(default=False, verbose_name='是否是定时通知'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_time',
            field=models.DateTimeField(null=True),
        ),
    ]
