# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0025_auto_20171105_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
